version: '3'

services:
  db:
    container_name: ecokakeibo-db
    image: mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: --innodb_use_native_aio=0 --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
  api:
    container_name: ecokakeibo-api
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ecokakeibo
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  mysql-data:
  bundle:
