class AddColumnToMeal < ActiveRecord::Migration[5.1]
  def change
    add_column :meals, :gyu_vw, :float
    add_column :meals, :gyu_fm, :float
    add_column :meals, :buta_vw, :float
    add_column :meals, :buta_fm, :float
    add_column :meals, :tori_vw, :float
    add_column :meals, :tori_fm, :float
    add_column :meals, :tamago_vw, :float
    add_column :meals, :tamago_fm, :float
    add_column :meals, :kome_vw, :float
    add_column :meals, :kome_fm, :float
    add_column :meals, :gohan_vw, :float
    add_column :meals, :gohan_fm, :float
    add_column :meals, :pan_vw, :float
    add_column :meals, :pan_fm, :float
    add_column :meals, :udon_vw, :float
    add_column :meals, :udon_fm, :float
    add_column :meals, :soumen_vw, :float
    add_column :meals, :soumen_fm, :float
    add_column :meals, :soba_vw, :float
    add_column :meals, :soba_fm, :float
    add_column :meals, :supagety_vw, :float
    add_column :meals, :supagety_fm, :float
    add_column :meals, :ramen_vw, :float
    add_column :meals, :ramen_fm, :float
    add_column :meals, :daikon_vw, :float
    add_column :meals, :daikon_fm, :float
    add_column :meals, :kabu_vw, :float
    add_column :meals, :kabu_fm, :float
    add_column :meals, :ninjin_vw, :float
    add_column :meals, :ninjin_fm, :float
    add_column :meals, :gobou_vw, :float
    add_column :meals, :gobou_fm, :float
    add_column :meals, :renkon_vw, :float
    add_column :meals, :renkon_fm, :float
    add_column :meals, :satoimo_vw, :float
    add_column :meals, :satoimo_fm, :float
    add_column :meals, :yamaimo_vw, :float
    add_column :meals, :yamaimo_fm, :float
    add_column :meals, :hakusai_vw, :float
    add_column :meals, :hakusai_fm, :float
    add_column :meals, :kyabetsu_vw, :float
    add_column :meals, :kyabetsu_fm, :float
    add_column :meals, :hourensou_vw, :float
    add_column :meals, :hourensou_fm, :float
    add_column :meals, :negi_vw, :float
    add_column :meals, :negi_fm, :float
    add_column :meals, :tamanegi_vw, :float
    add_column :meals, :tamanegi_fm, :float
    add_column :meals, :nasu_vw, :float
    add_column :meals, :nasu_fm, :float
    add_column :meals, :tomato_vw, :float
    add_column :meals, :tomato_fm, :float
    add_column :meals, :kyuri_vw, :float
    add_column :meals, :kyuri_fm, :float
    add_column :meals, :kabotya_vw, :float
    add_column :meals, :kabotya_fm, :float
    add_column :meals, :pyman_vw, :float
    add_column :meals, :pyman_fm, :float
    add_column :meals, :endou_vw, :float
    add_column :meals, :endou_fm, :float
    add_column :meals, :edamame_vw, :float
    add_column :meals, :edamame_fm, :float
    add_column :meals, :ingen_vw, :float
    add_column :meals, :ingen_fm, :float
    add_column :meals, :tomorokoshi_vw, :float
    add_column :meals, :tomorokoshi_fm, :float
    add_column :meals, :retasu_vw, :float
    add_column :meals, :retasu_fm, :float
    add_column :meals, :serori_vw, :float
    add_column :meals, :serori_fm, :float
    add_column :meals, :karifura_vw, :float
    add_column :meals, :karifura_fm, :float
    add_column :meals, :buro_vw, :float
    add_column :meals, :buro_fm, :float
    add_column :meals, :jaga_vw, :float
    add_column :meals, :jaga_fm, :float
    add_column :meals, :satsumaimo_vw, :float
    add_column :meals, :satsumaimo_fm, :float
    add_column :meals, :ninniku_vw, :float
    add_column :meals, :ninniku_fm, :float
    add_column :meals, :shitake_vw, :float
    add_column :meals, :shitake_fm, :float
    add_column :meals, :kuri_vw, :float
    add_column :meals, :kuri_fm, :float
    add_column :meals, :daizu_vw, :float
    add_column :meals, :daizu_fm, :float
    add_column :meals, :mikan_vw, :float
    add_column :meals, :mikan_fm, :float
    add_column :meals, :kiui_vw, :float
    add_column :meals, :kiui_fm, :float
    add_column :meals, :orange_vw, :float
    add_column :meals, :orange_fm, :float
    add_column :meals, :ringo_vw, :float
    add_column :meals, :ringo_fm, :float
    add_column :meals, :budou_vw, :float
    add_column :meals, :budou_fm, :float
    add_column :meals, :nashi_vw, :float
    add_column :meals, :nashi_fm, :float
    add_column :meals, :momo_vw, :float
    add_column :meals, :momo_fm, :float
    add_column :meals, :sumomo_vw, :float
    add_column :meals, :sumomo_fm, :float
    add_column :meals, :pain_vw, :float
    add_column :meals, :pain_fm, :float
    add_column :meals, :sakura_vw, :float
    add_column :meals, :sakura_fm, :float
    add_column :meals, :kaki_vw, :float
    add_column :meals, :kaki_fm, :float
    add_column :meals, :ichigo_vw, :float
    add_column :meals, :ichigo_fm, :float
    add_column :meals, :suika_vw, :float
    add_column :meals, :suika_fm, :float
    add_column :meals, :meron_vw, :float
    add_column :meals, :meron_fm, :float
    add_column :meals, :touhu_vw, :float
    add_column :meals, :touhu_fm, :float
    add_column :meals, :konnyaku_vw, :float
    add_column :meals, :konnyaku_fm, :float
    add_column :meals, :bata_vw, :float
    add_column :meals, :bata_fm, :float
    add_column :meals, :yoogle_vw, :float
    add_column :meals, :yoogle_fm, :float
    add_column :meals, :cheese_vw, :float
    add_column :meals, :cheese_fm, :float
    add_column :meals, :gyunyu_vw, :float
    add_column :meals, :gyunyu_fm, :float
    add_column :meals, :v_vw, :float
    add_column :meals, :v_fm, :float
    add_column :meals, :sio_vw, :float
    add_column :meals, :sio_fm, :float
    add_column :meals, :syoyu_vw, :float
    add_column :meals, :syoyu_fm, :float
    add_column :meals, :sake_vw, :float
    add_column :meals, :sake_fm, :float
    add_column :meals, :miso_vw, :float
    add_column :meals, :miso_fm, :float
    add_column :meals, :kecha_vw, :float
    add_column :meals, :kecha_fm, :float
    add_column :meals, :kosyo_vw, :float
    add_column :meals, :kosyo_fm, :float
    add_column :meals, :kary_vw, :float
    add_column :meals, :kary_fm, :float
    add_column :meals, :komugi_vw, :float
    add_column :meals, :komugi_fm, :float
    add_column :meals, :satou_vw, :float
    add_column :meals, :satou_fm, :float
    add_column :meals, :su_vw, :float
    add_column :meals, :su_fm, :float
    add_column :meals, :syokubutsuyu_vw, :float
    add_column :meals, :syokubutsuyu_fm, :float
    add_column :meals, :oliveoil_vw, :float
    add_column :meals, :oliveoil_fm, :float
    add_column :meals, :tya_vw, :float
    add_column :meals, :tya_fm, :float
    add_column :meals, :mugitya_vw, :float
    add_column :meals, :mugitya_fm, :float
    add_column :meals, :tea_vw, :float
    add_column :meals, :tea_fm, :float
    add_column :meals, :coffee_vw, :float
    add_column :meals, :coffee_fm, :float
    add_column :meals, :orangejuce_vw, :float
    add_column :meals, :orangejuce_fm, :float
    add_column :meals, :lemonjuce_vw, :float
    add_column :meals, :lemonjuce_fm, :float

  end
end
